
import { MenuItem, Room, Translation } from './types';

export const TRANSLATIONS: Record<'en' | 'mm', Translation> = {
  en: {
    dashboard: "Dashboard",
    rooms: "Rooms",
    menu: "Menu",
    available: "Available",
    occupied: "Occupied",
    cleaning: "Cleaning",
    reserved: "Reserved",
    maintenance: "Maintenance",
    startSession: "Start Session",
    endSession: "End Session",
    pauseSession: "Pause",
    resumeSession: "Resume",
    guests: "Guests",
    activeRooms: "Active Rooms",
    revenue: "Total Revenue",
    totalGuests: "Total Guests",
    avgDuration: "Avg. Session",
    serviceCalls: "Service Calls",
    searchMenu: "Search menu...",
    billSummary: "Bill Summary",
    roomCharges: "Room Charges",
    foodAndDrinks: "Food & Drinks",
    subtotal: "Subtotal",
    total: "TOTAL",
    cancel: "Cancel",
    confirm: "Confirm",
    addItems: "Add Items",
    printBill: "Print Bill",
    checkout: "Checkout",
    callWaiter: "Call Waiter",
    duration: "Duration",
    price: "Price",
    qty: "Qty",
    tax: "Tax (5%)",
    service: "Service (10%)",
    discount: "Discount",
    settings: "Settings",
    save: "Save",
    delete: "Delete",
    category: "Category",
    status: "Status",
    actions: "Actions",
    start: "Start Session",
    notes: "Notes",
    waiter: "Waiter",
    memberCard: "Member Card",
    specialRequest: "Special Request...",
    popular: "Popular",
    minimumCharge: "Minimum Charge Applied",
    paused: "Paused",
    login: "Login",
    username: "Username",
    password: "Password",
    logout: "Logout",
    edit: "Edit",
    paymentMethod: "Payment Method",
    amountTendered: "Amount Tendered",
    change: "Change",
    paid: "Paid",
    active: "Active",
    inactive: "Inactive",
    floor: "Floor",
    capacity: "Capacity",
    hourlyRate: "Hourly Rate"
  },
  mm: {
    dashboard: "ဒက်ရှ်ဘုတ်",
    rooms: "အခန်းများ",
    menu: "မီနူး ပြင်ဆင်ရန်",
    available: "အားသည်",
    occupied: "သုံးစွဲနေသည်",
    cleaning: "သန့်ရှင်းရေး",
    reserved: "ကြိုတင်မှာထားသည်",
    maintenance: "ပြင်ဆင်နေသည်",
    startSession: "စတင်မည်",
    endSession: "ပြီးဆုံးမည်",
    pauseSession: "ခေတ္တရပ်မည်",
    resumeSession: "ဆက်သွားမည်",
    guests: "ဧည့်သည်",
    activeRooms: "အသုံးပြုနေသော အခန်းများ",
    revenue: "စုစုပေါင်း ဝင်ငွေ",
    totalGuests: "စုစုပေါင်း ဧည့်သည်",
    avgDuration: "ပျမ်းမျှကြာချိန်",
    serviceCalls: "ဝန်ဆောင်မှုခေါ်ဆိုမှု",
    searchMenu: "မီနူး ရှာရန်...",
    billSummary: "ကျသင့်ငွေ စာရင်း",
    roomCharges: "အခန်းခ",
    foodAndDrinks: "အစားအသောက်",
    subtotal: "ပေါင်းလဒ်",
    total: "စုစုပေါင်း ကျသင့်ငွေ",
    cancel: "မလုပ်တော့ပါ",
    confirm: "အတည်ပြုသည်",
    addItems: "မှာယူမည်",
    printBill: "ဘေလ် ထုတ်မည်",
    checkout: "ငွေရှင်းမည်",
    callWaiter: "ဝန်ထမ်းခေါ်မည်",
    duration: "ကြာချိန်",
    price: "ဈေးနှုန်း",
    qty: "အရေအတွက်",
    tax: "အခွန် (၅%)",
    service: "ဝန်ဆောင်ခ (၁၀%)",
    discount: "လျှော့စျေး",
    settings: "ဆက်တင်များ",
    save: "သိမ်းဆည်းမည်",
    delete: "ဖျက်မည်",
    category: "အမျိုးအစား",
    status: "အခြေအနေ",
    actions: "လုပ်ဆောင်ချက်များ",
    start: "စတင်မည်",
    notes: "မှတ်ချက်",
    waiter: "ဝန်ထမ်း",
    memberCard: "အသင်းဝင်ကတ်",
    specialRequest: "အထူးတောင်းဆိုချက်...",
    popular: "လူကြိုက်များ",
    minimumCharge: "အနည်းဆုံး ကျသင့်ငွေ",
    paused: "ရပ်ထားသည်",
    login: "အကောင့်ဝင်ရန်",
    username: "အသုံးပြုသူအမည်",
    password: "စကားဝှက်",
    logout: "ထွက်မည်",
    edit: "ပြင်ဆင်မည်",
    paymentMethod: "ငွေပေးချေမှုပုံစံ",
    amountTendered: "ပေးငွေ",
    change: "ပြန်အမ်းငွေ",
    paid: "ပေးချေပြီး",
    active: "ဖွင့်ထားသည်",
    inactive: "ပိတ်ထားသည်",
    floor: "အလွှာ",
    capacity: "လူဦးရေ",
    hourlyRate: "တစ်နာရီနှုန်း"
  }
};

export const INITIAL_ROOMS: Room[] = [
  { id: "V-001", name: { en: "Standard 1", mm: "သာမန် ၁" }, type: "Standard", capacity: 8, hourlyRate: 8000, status: "available", floor: 1, session: null, minimumHours: 2, isActive: true },
  { id: "V-002", name: { en: "Standard 2", mm: "သာမန် ၂" }, type: "Standard", capacity: 8, hourlyRate: 8000, status: "available", floor: 1, session: null, minimumHours: 2, isActive: true },
  { id: "V-003", name: { en: "VIP 1", mm: "VIP ၁" }, type: "VIP", capacity: 12, hourlyRate: 15000, status: "available", floor: 1, minimumHours: 2, isActive: true, session: null },
  { id: "V-004", name: { en: "VIP 2", mm: "VIP ၂" }, type: "VIP", capacity: 12, hourlyRate: 15000, status: "available", floor: 2, session: null, minimumHours: 2, isActive: true },
  { id: "V-005", name: { en: "VVIP 1", mm: "VVIP ၁" }, type: "VVIP", capacity: 20, hourlyRate: 25000, status: "available", floor: 2, session: null, minimumHours: 2, isActive: true },
  { id: "V-006", name: { en: "VVIP 2", mm: "VVIP ၂" }, type: "VVIP", capacity: 20, hourlyRate: 25000, status: "reserved", floor: 2, session: null, minimumHours: 2, isActive: true },
];

export const INITIAL_MENU: MenuItem[] = [
  // Beer
  { id: "B001", name: { en: "Heineken", mm: "ဟိန္နီကင်" }, category: "Beer", price: 3500, image: "🍺", available: true, isPopular: true },
  { id: "B002", name: { en: "Tiger", mm: "တိုက်ဂါး" }, category: "Beer", price: 3000, image: "🍺", available: true, isPopular: true },
  { id: "B003", name: { en: "Dagon", mm: "ဒဂုံ" }, category: "Beer", price: 2500, image: "🍺", available: true },
  { id: "B004", name: { en: "Singha", mm: "ဆင်းဟ" }, category: "Beer", price: 3800, image: "🍺", available: true },
  // Food
  { id: "F001", name: { en: "Fried Chicken", mm: "ကြက်ကြော်" }, category: "Food", price: 8000, image: "🍗", available: true, isPopular: true },
  { id: "F002", name: { en: "French Fries", mm: "အာလူးချောင်းကြော်" }, category: "Food", price: 4000, image: "🍟", available: true },
  { id: "F003", name: { en: "Fried Rice", mm: "ထမင်းကြော်" }, category: "Food", price: 6000, image: "🍛", available: true },
  { id: "F004", name: { en: "BBQ Platter", mm: "အကင်စုံ" }, category: "Food", price: 25000, image: "🍖", available: true },
  // Drinks
  { id: "D001", name: { en: "Cola", mm: "ကိုလာ" }, category: "Soft Drinks", price: 1500, image: "🥤", available: true, isPopular: true },
  { id: "D002", name: { en: "Water", mm: "ရေသန့်" }, category: "Soft Drinks", price: 1000, image: "💧", available: true },
  { id: "D003", name: { en: "Red Bull", mm: "Red Bull" }, category: "Soft Drinks", price: 2500, image: "⚡", available: true },
  // Liquor
  { id: "L001", name: { en: "Chivas 12Y", mm: "Chivas 12Y" }, category: "Liquor", price: 120000, image: "🥃", available: true },
  { id: "L002", name: { en: "Johnnie Walker Red", mm: "JW Red" }, category: "Liquor", price: 85000, image: "🥃", available: true },
  // Snacks
  { id: "S001", name: { en: "Mixed Nuts", mm: "အစေ့အဆံ" }, category: "Snacks", price: 8000, image: "🥜", available: true },
  { id: "S002", name: { en: "Potato Chips", mm: "အာလူးကြော်" }, category: "Snacks", price: 3000, image: "🥡", available: true },
  // Fruit
  { id: "FR01", name: { en: "Fruit Platter (L)", mm: "သစ်သီးပန်းကန် (ကြီး)" }, category: "Fruit Platter", price: 20000, image: "🍉", available: true },
];

export const CATEGORIES = ["All", "Beer", "Food", "Soft Drinks", "Liquor", "Snacks", "Fruit Platter"];

export const WAITERS = ["Aung Aung", "Kyaw Kyaw", "Mya Mya", "Thida"];
